# Generated by Django 6.0.3 on 2026-04-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbuilder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='user',
        ),
        migrations.AddField(
            model_name='sheet',
            name='margin_cm',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
        migrations.AddField(
            model_name='sheet',
            name='spacing_cm',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=10),
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='sheetbuilder.sheet'),
        ),
    ]
