# Generated by Django 6.0.3 on 2026-04-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbuilder', '0002_remove_uploadasset_user_sheet_margin_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadasset',
            name='upscaled_file',
            field=models.ImageField(blank=True, null=True, upload_to='niron/upscaled/'),
        ),
        migrations.CreateModel(
            name='SheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('lock_ratio', models.BooleanField(default=True)),
                ('use_processed', models.BooleanField(default=False)),
                ('use_upscaled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_items', to='sheetbuilder.uploadasset')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sheetbuilder.sheet')),
            ],
        ),
    ]
