# Generated by Django 6.0.3 on 2026-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbuilder', '0003_uploadasset_upscaled_file_sheetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='x_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sheetitem',
            name='y_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
