# Generated by Django 6.0.3 on 2026-06-13 08:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbuilder', '0004_sheetitem_x_cm_sheetitem_y_cm_alter_sheet_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='rotation',
            field=models.PositiveSmallIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='margin_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='spacing_cm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=10),
        ),
    ]
